baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'Tech & IT Blog'

params:
  cookies:
    enable: true
    content: This site uses cookies. By continuing to use this website, you agree to their use.
    button: I Accept
  footer_left_label: "Tech & IT Blog"
  footer_middle_label: "Veterinary Clinic"
  footer_right_label: ""
  banner:
    image: /images/carmen.webp
    #bannerClass: bg-fit h-screen-50
    bannerStyle: |
      background-position: 50% 19%;
    text: |
      Tech & IT Blog  
      [Veterinary Clinic Dobersberg](//tierklinikdobersberg.at)
menu:
  footer_left:
    - identifier: home
      name: Home
      url: /
  footer_middle:
    - identifier: privacy-statement
      name: Privacy Statement
      url: /about/#privacy-statement
    - identifier: imprint
      name: Imprint
      url: /about/#Imprint
    - identifier: github
      name: Github
      url: https://github.com/tierklinik-dobersberg
  footer_right:
  - identifier: cc
    name: © 2021 Patrick Pacher
    url: /about-author/
  - identifier: hugo
    name: Built with ❤️ using Hugo
    url: https://gohugo.io
  - identifier: github
    url: https://github.com/tierklinik-dobersberg/tech-blog
    params:
      image: /images/github-mark.png
      image_dark: /images/github-mark-light.png
      image_classes: mb-4
  main:
#  - identifier: categories
#    name: Categories
#    url: /categories/
#    weight: 1
#  - identifier: nomad
#    name: Nomad
#    url: /categories/nomad/
#    parent: categories
#    weight: 0
  - identifier: posts
    name: Blog
    url: /posts/
    weight: 1
  - identifier: website
    name: Tierklinik Dobersberg
    params:
      class: button
    url: https://tierklinikdobersberg.at
    weight: 0

module:
  hugoVersion:
    extended: false
    min: "0.75.0"

build:
  # Used by PurgeCSS
  writeStats: true
